api_platform:
  description: "API publique du contenu des CaenCamp"
  version: "0.9.0"
  mapping:
    paths: ["%kernel.project_dir%/src/Entity/Internal"] # "%kernel.project_dir%/src/Entity", 
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  show_webby: false # hides the spider mascot
  collection:
    pagination:
      client_items_per_page: true
      items_per_page_parameter_name: itemsPerPage
      items_per_page: 10
      maximum_items_per_page: 50
