name: phpunit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          php-version: "7.4"

      - uses: php-actions/composer@v4
        with:
          php-version: "7.4"

      - name: PHPUnit
        uses: chindit/actions-phpunit-symfony@master
        with:
          php-version: "7.4"
